# SITE CONFIGURATION
baseurl:
url: "https://josephcrispell.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Joseph Crispell
user_title: Data Scientist
user_description: Programmer interested in all types of data and analyses
description: "Blog about things that interest me"
avatar: assets/img/WebsiteLogo.png
favicon: assets/img/WebsiteLogo.png  

# Header and footer text
header_text: Interesting things
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href='https://github.com/sylhare/Type-on-Strap'>Type on Strap</a> and <a href='https://github.com/nrandecker/particle'>particle</a> themes.

# Blog
excerpt: true                                           # Create excerpt of blog content (first 250 characters). "false" to disable
post_navigation: true                                   # Add previous and next buttons
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics: "UA-109829558-1"                      # Tracking ID, e.g. "UA-000000-01"
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "blog/page:num" # Note pagination only works on index.html file. So created one in new folder blog/

# PROJECTS
collections:
  projects:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]
